#ifndef SIMPLEPIM_QUALIFICATION_PARAM_H
#define SIMPLEPIM_QUALIFICATION_PARAM_H

#include <stdint.h>

typedef uint32_t T;

#define SIMPLEPIM_QUALIFICATION_DPU_COUNT 1
#define SIMPLEPIM_QUALIFICATION_ELEMENTS 256
#define SIMPLEPIM_QUALIFICATION_TASKLETS 12
#define SIMPLEPIM_QUALIFICATION_VALUE_BYTES 4
#define SIMPLEPIM_QUALIFICATION_INPUT_BYTES \
    (2 * SIMPLEPIM_QUALIFICATION_ELEMENTS * SIMPLEPIM_QUALIFICATION_VALUE_BYTES)
#define SIMPLEPIM_QUALIFICATION_OUTPUT_BYTES \
    (SIMPLEPIM_QUALIFICATION_ELEMENTS * SIMPLEPIM_QUALIFICATION_VALUE_BYTES)

#if !defined(NR_TASKLETS) || NR_TASKLETS != SIMPLEPIM_QUALIFICATION_TASKLETS
#error "SimplePIM qualification must be compiled with exactly 12 tasklets"
#endif

#if SIMPLEPIM_QUALIFICATION_INPUT_BYTES % 8 != 0 || \
    SIMPLEPIM_QUALIFICATION_OUTPUT_BYTES % 8 != 0
#error "SimplePIM qualification payload sizes must be 8-byte aligned"
#endif

#endif
