from __future__ import annotations

DEMO_BOOKS = [
    {
        "title": "Foundation",
        "author": "Isaac Asimov",
        "isbn": "9780553293357",
        "description": "A long-range plan uses mathematics and history to reduce a galactic dark age.",
        "genres": ["science fiction", "strategy", "classic"],
        "published_year": 1951,
        "source": "demo",
    },
    {
        "title": "The Left Hand of Darkness",
        "author": "Ursula K. Le Guin",
        "isbn": "9780441478125",
        "description": "An envoy explores culture, identity, diplomacy, and trust on a frozen world.",
        "genres": ["science fiction", "social", "political"],
        "published_year": 1969,
        "source": "demo",
    },
    {
        "title": "A Wizard of Earthsea",
        "author": "Ursula K. Le Guin",
        "isbn": "9780547773742",
        "description": "A young wizard learns power, fear, names, and responsibility across an island world.",
        "genres": ["fantasy", "coming of age", "magic"],
        "published_year": 1968,
        "source": "demo",
    },
    {
        "title": "The Three-Body Problem",
        "author": "Cixin Liu",
        "isbn": "9780765382030",
        "description": "First contact, orbital chaos, scientific mystery, and civilizational risk.",
        "genres": ["science fiction", "first contact", "hard science fiction"],
        "published_year": 2008,
        "source": "demo",
    },
    {
        "title": "The Name of the Rose",
        "author": "Umberto Eco",
        "isbn": "9780156001311",
        "description": "A medieval monastery mystery mixes philosophy, books, politics, and investigation.",
        "genres": ["mystery", "historical fiction", "philosophy"],
        "published_year": 1980,
        "source": "demo",
    },
    {
        "title": "The Dispossessed",
        "author": "Ursula K. Le Guin",
        "isbn": "9780061054884",
        "description": "A physicist moves between rival societies while questioning freedom and obligation.",
        "genres": ["science fiction", "political", "utopian"],
        "published_year": 1974,
        "source": "demo",
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "isbn": "9780593135204",
        "description": "A lone astronaut solves engineering puzzles to save Earth from an astrophysical threat.",
        "genres": ["science fiction", "engineering", "survival"],
        "published_year": 2021,
        "source": "demo",
    },
    {
        "title": "Piranesi",
        "author": "Susanna Clarke",
        "isbn": "9781635575637",
        "description": "A quiet labyrinth of halls, tides, memory, and wonder hides a strange truth.",
        "genres": ["fantasy", "mystery", "literary"],
        "published_year": 2020,
        "source": "demo",
    },
    {
        "title": "Neuromancer",
        "author": "William Gibson",
        "isbn": "9780441569595",
        "description": "A hacker is hired for a dangerous cyberspace job involving AI and corporate power.",
        "genres": ["science fiction", "cyberpunk", "technology"],
        "published_year": 1984,
        "source": "demo",
    },
    {
        "title": "The Fifth Season",
        "author": "N. K. Jemisin",
        "isbn": "9780316229296",
        "description": "A broken world of seismic disaster, oppression, hidden power, and survival.",
        "genres": ["fantasy", "apocalyptic", "social"],
        "published_year": 2015,
        "source": "demo",
    },
    {
        "title": "Snow Crash",
        "author": "Neal Stephenson",
        "isbn": "9780553380958",
        "description": "A fast cyberpunk satire about language, virtual worlds, networks, and power.",
        "genres": ["science fiction", "cyberpunk", "satire"],
        "published_year": 1992,
        "source": "demo",
    },
    {
        "title": "The Murder of Roger Ackroyd",
        "author": "Agatha Christie",
        "isbn": "9780062073563",
        "description": "A village murder investigation uses misdirection, testimony, and a famous detective.",
        "genres": ["mystery", "detective", "classic"],
        "published_year": 1926,
        "source": "demo",
    },
]
